# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: go-test
        name: run go tests
        language: system
        entry: go test
        types: [go]
        files: '.go'
        pass_filenames: false
    -   id: go-lint
        name: lint go
        language: system
        entry: golangci-lint run -e gocritic 
        types: [go]
        files: '.go'
        pass_filenames: false
    -   id: staticcheck
        name: staticcheck
        language: system
        entry: staticcheck ./...
        types: [go]
        files: '.go'
        pass_filenames: false
    -   id: gocyclo
        name: gocyclo
        language: system
        entry: gocyclo -over 10 .
        types: [go]
        files: '.go'
        pass_filenames: false
