# fly.toml app configuration file generated for gowebapp-quiet-hill-3067-quiet-butterfly-4356 on 2023-11-18T00:36:24+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gowebapp"
primary_region = "waw"

[build]
  dockerfile = "prod.Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
